Refine script.

diff --git a/.github/workflows/release-en.yml b/.github/workflows/release-en.yml
--- a/.github/workflows/release-en.yml
+++ b/.github/workflows/release-en.yml
@@ -113,7 +113,7 @@ jobs:
           username: root
           key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
           port: 22
-          envs: SRS_TAG,SEARCH_APIKEY,SRS_DROPLET_PIP
+          envs: SRS_TAG,SRS_MAJOR,SEARCH_APIKEY,SRS_DROPLET_PIP
           script: |
             #
             # Restart HTTPX
@@ -122,7 +122,7 @@ jobs:
               docker rm -f httpx; sleep 0.3;
             done
             docker run -d -it --restart always \
-              --name httpx -p 20080:80 ossrs/httpx:v1.0.19 \
+              --name docs-httpx -p 20080:80 ossrs/httpx:v1.0.19 \
               ./bin/httpx-static -http 80 \
               -proxy http://$SRS_DROPLET_PIP:8107/lts/ \
               -proxy http://$SRS_DROPLET_PIP:8108/multi_search
@@ -132,7 +132,8 @@ jobs:
               if [[ $(docker ps -f name=docs |wc -l) -eq 1 ]]; then echo "Killed"; break; fi;
               docker rm -f docs; sleep 0.3;
             done
-            docker run -d -it --restart always --privileged --name docs -p 8107:80 ossrs/docs:en-$SRS_TAG
+            docker pull ossrs/docs:en-$SRS_TAG && docker pull ossrs/docs:en-$SRS_MAJOR
+            docker run -d -it --restart always --privileged --name docs-docs -p 8107:80 ossrs/docs:en-$SRS_TAG
             #
             # Use 8107/tcp as port.
             sed -i 's/host.docker.internal:3000/host.docker.internal:8107/g' /root/search/scraper.json
@@ -142,7 +143,7 @@ jobs:
               if [[ $(docker ps -f name=typesense |wc -l) -eq 1 ]]; then echo "Killed"; break; fi;
               docker rm -f typesense; sleep 0.3;
             done
-            docker run -d -it --restart always --privileged --name typesense -v /root/search/data:/data -p $SRS_DROPLET_PIP:8108:8108 \
+            docker run -d -it --restart always --privileged --name docs-typesense -v /root/search/data:/data -p $SRS_DROPLET_PIP:8108:8108 \
               typesense/typesense:0.22.1 --enable-cors --data-dir /data --api-key=$SEARCH_APIKEY
             #
             # Restart search scraper
@@ -152,8 +153,14 @@ jobs:
             done
             # Replace the BASE_URL
             sed -i 's|.*url.*host.docker.internal:8107.*|      "url": "http://host.docker.internal:8107/",|g' /root/search/scraper.json
-            docker run --rm --privileged --name search-scraper --add-host host.docker.internal:$SRS_DROPLET_PIP -e UPDATE_NB_HITS=0 \
+            docker run --rm --privileged --name docs-search-scraper --add-host host.docker.internal:$SRS_DROPLET_PIP -e UPDATE_NB_HITS=0 \
               -e TYPESENSE_HOST=host.docker.internal -e TYPESENSE_API_KEY=$SEARCH_APIKEY -e TYPESENSE_PORT=8108 \
               -e TYPESENSE_PROTOCOL=http -v /root/search/scraper.json:/config.json -e CONFIG=/config.json \
               typesense/docsearch-scraper
+            #
+            # Cleanup old docker images.
+            for image in $(docker images |grep '<none>' |awk '{print $3}'); do
+              docker rmi -f $image
+              echo "Remove image $image, r0=$?"
+            done
 
